# Generated by Django 4.1.3 on 2022-11-21 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='market_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.marketplace'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='zip_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.zipcode'),
        ),
    ]
